// utils/exportPdf.js — replaces the web app's `window.print()`.
// Builds branded, printable HTML and turns it into a real PDF via expo-print,
// then lets the user save/share it via expo-sharing.
//
// LOGO: loaded from the local assets folder (./assets/logo.jpg) at export
// time, so you can just swap that file to change the logo — no code edits
// needed. Adjust the require() path below if you place it elsewhere in
// your project structure.

import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Asset } from "expo-asset";
import * as FileSystem from "expo-file-system/legacy";

import logoBase64 from "../../assets/logoBase64.js"; // auto-generated by scripts/generate-logo.js

const APP_NAME = "Shopping List";
const APP_TAGLINE = "Never forget to buy";


function getLogoDataUri() {
  return `data:image/png;base64,${logoBase64}`;
}

// ---- Palette ------------------------------------------------------------
const COLORS = {
  ink: "#1c1610",        // near-black warm charcoal (matches logo bg)
  gold: "#b8863f",       // logo gold
  goldLight: "#e8c78a",
  cream: "#fbf7f0",
  pendingBg: "#fff1e8",
  pendingAccent: "#e8703a", // warm coral for "to buy"
  boughtBg: "#eaf6ee",
  boughtAccent: "#2f9e5c",  // green for "purchased"
  rowAlt: "#faf8f4",
  border: "#e8e2d6",
  textMuted: "#8a8175",

    // Grand total
  totalBg: "#013cfe",
  totalAccent: "#ffffff",
};

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

function rowsHtml(rows, accent) {
  if (rows.length === 0) {
    return `<tr><td colspan="6" style="padding:16px 8px;text-align:center;color:${COLORS.textMuted};font-size:12.5px;font-style:italic;">Nothing here yet</td></tr>`;
  }
  return rows
    .map(
      (r, i) => `
      <tr style="background:${i % 2 === 0 ? "#ffffff" : COLORS.rowAlt};">
        <td style="padding:9px 10px;font-weight:600;color:${COLORS.ink};">${escapeHtml(r.name)}</td>
        <td style="padding:9px 10px;color:${COLORS.textMuted};">
          <span style="background:${accent}18;color:${accent};padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600;">${escapeHtml(r.category)}</span>
        </td>
        <td style="padding:9px 10px;">${r.qty} ${escapeHtml(r.unit)}</td>
        <td style="padding:9px 10px;">${r.price !== "" && r.price != null ? `\u20b9${r.price}` : "-"}</td>
        <td style="padding:9px 10px;font-weight:700;color:${COLORS.ink};">${r.price !== "" && r.price != null ? `\u20b9${(Number(r.price) * Number(r.qty)).toFixed(0)}` : "-"}</td>
        <td style="padding:9px 10px;color:${COLORS.textMuted};">${escapeHtml(r.note || "-")}</td>
      </tr>`
    )
    .join("");
}

function sectionTable(title, rows, accent, bg, total, totalLabel) {
  return `
  <div style="margin-top:22px;border:1px solid ${COLORS.border};border-radius:12px;overflow:hidden;">
    <div style="background:${bg};padding:10px 14px;border-bottom:2px solid ${accent};display:flex;align-items:center;">
      <span style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${accent};margin-right:8px;"></span>
      <span style="font-family:'Arial',sans-serif;font-size:15px;font-weight:700;color:${accent};">${title}</span>
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:12.5px;">
      <thead>
        <tr style="text-align:left;border-bottom:1px solid ${COLORS.border};">
          <th style="padding:8px 10px;color:${COLORS.textMuted};font-size:11px;text-transform:uppercase;letter-spacing:0.03em;">Item</th>
          <th style="padding:8px 10px;color:${COLORS.textMuted};font-size:11px;text-transform:uppercase;letter-spacing:0.03em;">Category</th>
          <th style="padding:8px 10px;color:${COLORS.textMuted};font-size:11px;text-transform:uppercase;letter-spacing:0.03em;">Qty</th>
          <th style="padding:8px 10px;color:${COLORS.textMuted};font-size:11px;text-transform:uppercase;letter-spacing:0.03em;">Price</th>
          <th style="padding:8px 10px;color:${COLORS.textMuted};font-size:11px;text-transform:uppercase;letter-spacing:0.03em;">Line total</th>
          <th style="padding:8px 10px;color:${COLORS.ink};font-size:11px;text-transform:uppercase;letter-spacing:0.03em;">Note</th>
        </tr>
      </thead>
      <tbody>${rowsHtml(rows, accent)}</tbody>
    </table>
    <div style="background:${bg};padding:9px 14px;text-align:right;border-top:1px solid ${COLORS.border};">
      <span style="font-size:12px;color:${COLORS.ink};margin-right:6px;">${totalLabel}</span>
      <span style="font-size:14px;font-weight:800;color:${COLORS.ink};">\u20b9${total.toFixed(0)}</span>
    </div>
  </div>`;
}

export async function exportListPdf({ listName, profileName, pendingItems, boughtItems, pendingTotal, boughtTotal }) {
  const grandTotal = boughtTotal + pendingTotal;
  const logoDataUri = await getLogoDataUri();
  console.log("Logo data URI length:", logoDataUri.length);

  // The whole document lives inside ONE table whose <thead> repeats on
  // every printed page — that's how the branded header (logo + app name)
  // shows up at the top of each page, not just the first.
  const html = `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        @page { margin: 0; }
        body { margin: 0; font-family: Inter, -apple-system, sans-serif; color: ${COLORS.ink}; background: #ffffff; }
        table.page-shell { width: 100%; border-collapse: collapse; }
        thead.brand-head { display: table-header-group; }
        tfoot.brand-foot { display: table-footer-group; }
      </style>
    </head>
    <body>
      <table class="page-shell">
        <thead class="brand-head">
          <tr>
            <td style="padding:0;">
              <div style="background:#ffffff;padding:16px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;border-bottom:3px solid ${COLORS.gold};">
                <img src="${logoDataUri}" style="width:38px;height:38px;border-radius:8px;object-fit:cover;margin-bottom:6px;" />
                <div style="font-family:'Arial',sans-serif;font-size:16px;font-weight:800;color:${COLORS.ink};line-height:1.1;">${APP_NAME}</div>
                <div style="margin-top:10px;font-size:10px;color:${COLORS.ink};letter-spacing:0.04em;text-transform:uppercase;">${APP_TAGLINE}</div>
              </div>
            </td>
          </tr>
        </thead>
        <tfoot class="brand-foot">
          <tr><td style="height:18px;"></td></tr>
        </tfoot>
        <tbody>
          <tr>
            <td style="padding:24px 28px 32px 28px;">

              <h1 style="font-family:'Arial',cursive;font-size:23px;margin:0 0 2px 0;color:${COLORS.ink};">${escapeHtml(listName || "Shopping List")}</h1>
              <p style="font-size:12px;color:${COLORS.textMuted};margin:0 0 4px 0;">${profileName ? `${escapeHtml(profileName)} \u00b7 ` : ""}${new Date().toLocaleDateString()}</p>

              ${pendingItems.length > 0 ? sectionTable("Items to buy", pendingItems, COLORS.pendingAccent, COLORS.pendingBg, pendingTotal, "Pending total") : ""}
              ${boughtItems.length > 0 ? sectionTable("Purchased items", boughtItems, COLORS.boughtAccent, COLORS.boughtBg, boughtTotal, "Bought total") : ""}

              ${
                pendingItems.length > 0 || boughtItems.length > 0
                  ? `<div style="margin-top:22px;background:${COLORS.totalBg};border-radius:12px;padding:14px 18px;display:flex;justify-content:space-between;align-items:center;">
                <span style="color:${COLORS.totalAccent};font-size:19px;font-weight:900;">Grand total</span>
                <span style="color:${COLORS.totalAccent};font-size:19px;font-weight:800;">\u20b9${grandTotal.toFixed(0)}</span>
              </div>`
                  : ""
              }
              <p style="margin-top:24px;text-align:center;font-size:15px;font-weight:800;color:${COLORS.textMuted};">Generated by ${APP_NAME} - Never Forget a Thing</p>

            </td>
          </tr>
        </tbody>
      </table>
    </body>
  </html>`;

  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: "Export list" });
  }
  return uri;
}