// utils/exportPdf.js — replaces the web app's `window.print()`.
// Builds branded, printable HTML and turns it into a real PDF via expo-print,
// then lets the user save/share it via expo-sharing.
//
// LOGO: generated into ../../assets/logoBase64.js by scripts/generate-logo.js,
// so just re-run that script to change the logo.

import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system/legacy";

import { warn } from "./logger";
import logoBase64 from "../../assets/logoBase64.js"; // auto-generated by scripts/generate-logo.js

const APP_NAME = "MindCart";
const APP_TAGLINE = "Never forget to buy";

// ---- Palette ------------------------------------------------------------
const COLORS = {
  ink: "#1c1610",          // near-black warm charcoal (matches logo bg)
  inkSoft: "#3a3128",
  gold: "#b8863f",         // logo gold
  goldLight: "#e8c78a",
  cream: "#fbf7f0",
  pendingBg: "#fff4ec",
  pendingAccent: "#e8703a", // warm coral for "to buy"
  boughtBg: "#edf7f0",
  boughtAccent: "#2f9e5c",  // green for "purchased"
  rowAlt: "#faf8f4",
  border: "#e8e2d6",
  textMuted: "#8a8175",
};

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

// File name like "MindCart_2026-09-30_14-05-33.pdf" (local time, no colons
// or spaces so it's safe on every file system).
function buildPdfFileName() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, "0");
  const stamp = `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}_${p(d.getHours())}-${p(d.getMinutes())}-${p(d.getSeconds())}`;
  return `${APP_NAME}_${stamp}.pdf`;
}

// "30 Sep 2026 · 2:05 PM" — done by hand so it looks the same on every device.
function prettyDateTime() {
  const d = new Date();
  const h = d.getHours();
  const h12 = h % 12 === 0 ? 12 : h % 12;
  const min = String(d.getMinutes()).padStart(2, "0");
  return `${d.getDate()} ${MONTHS[d.getMonth()]} ${d.getFullYear()} \u00b7 ${h12}:${min} ${h >= 12 ? "PM" : "AM"}`;
}

function getLogoDataUri() {
  return `data:image/png;base64,${logoBase64}`;
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

// Indian digit grouping (12,34,567) — matches the ₹ default.
function formatAmount(num, forceInt) {
  const x = Number(num);
  if (!isFinite(x)) return "0";
  const decimals = forceInt || Number.isInteger(x) ? 0 : 2;
  const [intPart, frac] = Math.abs(x).toFixed(decimals).split(".");
  const last3 = intPart.slice(-3);
  const rest = intPart.slice(0, -3);
  const grouped = (rest ? rest.replace(/\B(?=(\d{2})+(?!\d))/g, ",") + "," : "") + last3;
  return `${x < 0 ? "-" : ""}${grouped}${frac ? "." + frac : ""}`;
}

function statusDot(accent, done) {
  return done
    ? `<span style="display:inline-block;width:15px;height:15px;line-height:15px;border-radius:50%;background:${accent};color:#fff;font-size:10px;font-weight:800;text-align:center;">\u2713</span>`
    : `<span style="display:inline-block;width:11px;height:11px;border-radius:50%;border:1.6px solid ${accent};"></span>`;
}

function rowsHtml(rows, accent, done, sym) {
  if (rows.length === 0) {
    return `<tr><td colspan="6" style="padding:16px 8px;text-align:center;color:${COLORS.textMuted};font-size:12.5px;font-style:italic;">Nothing here yet</td></tr>`;
  }
  return rows
    .map((r, i) => {
      const hasPrice = r.price !== "" && r.price != null && Number(r.price) !== 0;
      return `
      <tr style="background:${i % 2 === 0 ? "#ffffff" : COLORS.rowAlt};page-break-inside:avoid;">
        <td style="padding:10px 0 10px 12px;width:22px;">${statusDot(accent, done)}</td>
        <td style="padding:10px 10px;font-weight:700;color:${done ? COLORS.inkSoft : COLORS.ink};">${escapeHtml(r.name)}</td>
        <td style="padding:10px 10px;">
          <span style="background:${accent}1a;color:${accent};padding:3px 9px;border-radius:10px;font-size:10.5px;font-weight:700;">${escapeHtml(r.category)}</span>
        </td>
        <td style="padding:10px 10px;text-align:center;white-space:nowrap;">${escapeHtml(r.qty)} <span style="color:${COLORS.textMuted};font-size:11px;">${escapeHtml(r.unit)}</span></td>
        <td style="padding:10px 10px;text-align:right;white-space:nowrap;font-weight:700;color:${hasPrice ? COLORS.ink : COLORS.textMuted};">${hasPrice ? `${sym}${formatAmount(r.price)}` : "\u2013"}</td>
        <td style="padding:10px 12px 10px 10px;color:${COLORS.textMuted};font-size:11.5px;font-style:${r.note ? "italic" : "normal"};">${escapeHtml(r.note || "\u2013")}</td>
      </tr>`;
    })
    .join("");
}

function thCell(label, align, extra = "") {
  return `<th style="padding:9px 10px;text-align:${align};color:${COLORS.textMuted};font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:0.06em;${extra}">${label}</th>`;
}

function sectionTable(title, rows, accent, bg, total, totalLabel, done, sym) {
  return `
  <div style="margin-top:22px;border:1px solid ${COLORS.border};border-radius:12px;">
    <div style="background:${bg};padding:11px 14px;border-bottom:2px solid ${accent};border-radius:11px 11px 0 0;display:flex;align-items:center;justify-content:space-between;">
      <span style="font-size:15px;font-weight:800;color:${accent};">${title}</span>
      <span style="background:${accent};color:#fff;font-size:10.5px;font-weight:800;padding:3px 10px;border-radius:10px;">${rows.length} ${rows.length === 1 ? "item" : "items"}</span>
    </div>
    <table style="width:100%;border-collapse:collapse;font-size:12.5px;">
      <thead>
        <tr style="border-bottom:1px solid ${COLORS.border};">
          ${thCell("", "left", "width:22px;padding-left:12px;")}
          ${thCell("Item", "left")}
          ${thCell("Category", "left")}
          ${thCell("Qty", "center")}
          ${thCell("Price", "right")}
          ${thCell("Note", "left")}
        </tr>
      </thead>
      <tbody>${rowsHtml(rows, accent, done, sym)}</tbody>
    </table>
    <div style="background:${bg};padding:10px 16px;text-align:right;border-top:1px solid ${COLORS.border};border-radius:0 0 11px 11px;">
      <span style="font-size:12px;color:${COLORS.textMuted};margin-right:8px;">${totalLabel}</span>
      <span style="font-size:15px;font-weight:800;color:${COLORS.ink};">${sym}${formatAmount(total, true)}</span>
    </div>
  </div>`;
}

function statCard(label, value, accent) {
  return `
  <div style="flex:1;border:1px solid ${COLORS.border};border-top:3px solid ${accent};border-radius:10px;padding:10px 12px;background:#ffffff;">
    <div style="font-size:9.5px;font-weight:700;letter-spacing:0.07em;text-transform:uppercase;color:${COLORS.textMuted};">${label}</div>
    <div style="margin-top:4px;font-size:18px;font-weight:800;color:${COLORS.ink};">${value}</div>
  </div>`;
}

export async function exportListPdf({ listName, profileName, pendingItems, boughtItems, pendingTotal, boughtTotal, currencySymbol }) {
  const sym = currencySymbol ? escapeHtml(currencySymbol) : "\u20b9";
  const grandTotal = boughtTotal + pendingTotal;
  const totalCount = pendingItems.length + boughtItems.length;
  const pct = totalCount > 0 ? Math.round((boughtItems.length / totalCount) * 100) : 0;
  const logoDataUri = getLogoDataUri();

  // The whole document lives inside ONE table whose <thead> repeats on
  // every printed page — that's how the branded header (logo + app name)
  // shows up at the top of each page, not just the first.
  const html = `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        @page { margin: 0; }
        * { -webkit-print-color-adjust: exact; print-color-adjust: exact; box-sizing: border-box; }
        body { margin: 0; font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: ${COLORS.ink}; background: #ffffff; }
        table.page-shell { width: 100%; border-collapse: collapse; }
        thead.brand-head { display: table-header-group; }
        tfoot.brand-foot { display: table-footer-group; }
        tr { page-break-inside: avoid; }
      </style>
    </head>
    <body>
      <table class="page-shell">
        <thead class="brand-head">
          <tr>
            <td style="padding:0;">
              <div style="background:${COLORS.ink};padding:14px 28px;display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid ${COLORS.gold};">
                <div style="display:flex;align-items:center;">
                  <img src="${logoDataUri}" style="width:40px;height:40px;border-radius:9px;object-fit:cover;border:1px solid ${COLORS.gold};margin-right:12px;" />
                  <div>
                    <div style="font-size:19px;font-weight:800;color:#ffffff;line-height:1.1;letter-spacing:0.01em;">${APP_NAME}</div>
                    <div style="margin-top:3px;font-size:9.5px;color:${COLORS.goldLight};letter-spacing:0.12em;text-transform:uppercase;">${APP_TAGLINE}</div>
                  </div>
                </div>
                <div style="font-size:10px;font-weight:700;color:${COLORS.goldLight};letter-spacing:0.14em;text-transform:uppercase;">Shopping list</div>
              </div>
            </td>
          </tr>
        </thead>
        <tfoot class="brand-foot">
          <tr><td style="height:18px;"></td></tr>
        </tfoot>
        <tbody>
          <tr>
            <td style="padding:26px 28px 32px 28px;">

              <h1 style="font-size:28px;font-weight:800;margin:0;color:${COLORS.ink};letter-spacing:-0.01em;">${escapeHtml(listName || "MindCart")}</h1>
              <div style="width:44px;height:3px;background:${COLORS.gold};border-radius:2px;margin:8px 0 10px 0;"></div>
              <p style="font-size:12px;color:${COLORS.textMuted};margin:0;">${profileName ? `${escapeHtml(profileName)} \u00b7 ` : ""}${prettyDateTime()}</p>

              ${
                totalCount > 0
                  ? `<div style="display:flex;gap:10px;margin-top:18px;">
                ${statCard("Total items", String(totalCount), COLORS.gold)}
                ${statCard("To buy", `${sym}${formatAmount(pendingTotal, true)}`, COLORS.pendingAccent)}
                ${statCard("Purchased", `${sym}${formatAmount(boughtTotal, true)}`, COLORS.boughtAccent)}
              </div>
              <div style="margin-top:14px;">
                <div style="display:flex;justify-content:space-between;font-size:11px;color:${COLORS.textMuted};margin-bottom:5px;">
                  <span>${boughtItems.length} of ${totalCount} items bought</span>
                  <span style="font-weight:800;color:${COLORS.boughtAccent};">${pct}%</span>
                </div>
                <div style="height:7px;background:${COLORS.border};border-radius:4px;">
                  <div style="height:7px;width:${pct}%;background:${COLORS.boughtAccent};border-radius:4px;"></div>
                </div>
              </div>`
                  : ""
              }

              ${pendingItems.length > 0 ? sectionTable("Items to buy", pendingItems, COLORS.pendingAccent, COLORS.pendingBg, pendingTotal, "Pending total", false, sym) : ""}
              ${boughtItems.length > 0 ? sectionTable("Purchased items", boughtItems, COLORS.boughtAccent, COLORS.boughtBg, boughtTotal, "Bought total", true, sym) : ""}

              ${
                totalCount > 0
                  ? `<div style="margin-top:22px;background:${COLORS.ink};border-radius:12px;padding:16px 20px;display:flex;justify-content:space-between;align-items:center;border-left:5px solid ${COLORS.gold};page-break-inside:avoid;">
                <div>
                  <div style="color:#ffffff;font-size:17px;font-weight:800;">Grand total</div>
                  <div style="color:${COLORS.goldLight};font-size:10.5px;margin-top:3px;">Pending + purchased</div>
                </div>
                <span style="color:${COLORS.goldLight};font-size:26px;font-weight:900;">${sym}${formatAmount(grandTotal, true)}</span>
              </div>`
                  : ""
              }

              <div style="margin-top:28px;text-align:center;">
                <div style="width:60px;height:2px;background:${COLORS.gold};border-radius:1px;margin:0 auto 10px auto;"></div>
                <p style="margin:0;font-size:11.5px;font-weight:700;color:${COLORS.textMuted};">Generated by ${APP_NAME} \u00b7 Never Forget a Thing</p>
              </div>

            </td>
          </tr>
        </tbody>
      </table>
    </body>
  </html>`;

  const { uri: tempUri } = await Print.printToFileAsync({ html });

  // printToFileAsync gives a random UUID file name — move it to a readable
  // "MindCart_<date>_<time>.pdf" so that's the name the user sees when saving.
  let uri = tempUri;
  try {
    const target = `${FileSystem.cacheDirectory}${buildPdfFileName()}`;
    await FileSystem.deleteAsync(target, { idempotent: true });
    await FileSystem.moveAsync({ from: tempUri, to: target });
    uri = target;
  } catch (e) {
    warn("PDF rename failed, using default name:", e?.message);
  }

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: "application/pdf", UTI: "com.adobe.pdf", dialogTitle: "Export list" });
  }
  return uri;
}